---
title: "Project 1"
author: "Nick Oliver"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
editor_options: 
  chunk_output_type: console
---

# Project 1

## Load Libraries

```{r load-libraries, results=FALSE, messages=FALSE}
library(RCurl)
library(stringr)
library(dplyr)
library(tidyr)
```

## Load Raw Data

```{r read-data}
file_url <- 'https://raw.githubusercontent.com/nolivercuny/data607/master/project1/tournamentinfo.txt'
raw_data <- getURL(file_url)
```

## Processing

Get rid of useless dashes
```{r}
data <- str_replace_all(raw_data,"-", "")
```

```{r}

split <- str_split(data, '\n', simplify = TRUE)

```

```{r}
split_values <- str_split(split, '\\|', simplify=TRUE)

```

```{r}
df <- as.data.frame(split_values) %>% filter(V1 != "", V1 != "\r")
```

```{r}
df_one <- df %>% filter(row_number() %% 2 == 1) 
names(df_one) <- df_one[1,]
df_two <- df %>% filter(row_number() %% 2 == 0)
names(df_two) <- df_two[1,]

```

```{r}
data <- bind_cols(df_one,df_two)
data <- subset(data, select=-c(11,22))
data <- data[-c(1),]
```

```{r}
data <- separate(data, 12, sep="/", into = c('USCF_ID','PRE_POST'))
data <- separate(data, 13, sep=">", into = c('Pre_Rating','Post_Rating'))
```