CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID INT PRIMARY KEY,
    PUBLISH_DATE TEXT,
    AUTHOR TEXT,
    SUBJECT TEXT,
    BYLINE TEXT,
    CATEGORY TEXT,
    BODY TEXT,
    SOURCE_URL TEXT NOT NULL,
    RETRIEVED_AT TEXT NOT NULL
)