---
title: "Final Project Presentation"
author: "Nick Oliver"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
editor_options: 
  chunk_output_type: console
---

# Are Web Publications Padding Their Articles For Ad Engagement?

My final project is an investigation into the question of if online web publications have been needlessly padding the length of articles in order to increase ad revenue. 

## Background

### Data Sources

My primary data source was the online news website Wired.com[^1]. Wired.com, initially founded as a print magazine, has been operating an online technology focuses web publication site since 1994. I chose Wired.com for two reasons, because they have a their entire backlog of articles going back to 1998 easily accessible via their site map and two because one of their articles was the initial inspiration for this project.

## Data Collection

```{r}
linksDf <- read.csv('final_project_links.csv', nrows=10)
```


## Data Manipulation

## Analysis

## Conclusions

Using the data I was able to obtain from Wired.com it is clear that there is a significant increase in online article length especially in recent years. 

## References

[^1]: Nast, C. (n.d.). The latest in technology, Science, Culture and Business. Wired. Retrieved December 5, 2021, from https://www.wired.com/. 